# Add this docker file as chat-agents
version: '3'
services:
  chat-agents:
    build:
      context: ./microservices/chat-agents-executor
      args:
        - LOGGER_URL=${LOGGER_URL:?Logger URL is required}
        - LOGGER_TOKEN=${LOGGER_TOKEN:?Logger Token is required}
        - GEMINI_API_KEY=${GEMINI_API_KEY:?Gemini API Key is required}
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - LOGGER_URL=${LOGGER_URL}
      - LOGGER_TOKEN=${LOGGER_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_HOST=mongodb://mongodb:27017/chat-agents
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672

  user-facing-api:
    container_name: user-facing-api
    build:
      context: ./microservices/user-facing-api
      args:
        - USER_API_HOST=${USER_API_HOST}
        - JWT_SECRET=${JWT_SECRET:?JWT Secret is required}
        - ADMIN_PASS=${ADMIN_PASS:?Admin Password is required}
        - ADMIN_EMAIL=${ADMIN_EMAIL:?Admin Email is required}
        - LOGGER_URL=${LOGGER_URL:?Logger URL is required}
        - LOGGER_TOKEN=${LOGGER_TOKEN:?Logger Token is required}
    depends_on:
      - mongodb
      - queue-api-gateway
    ports:
      - "4000:4000"
    environment:
      - HOST=${USER_API_HOST:-localhost}
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/user-facing-api
      - PROMPT_URL=http://queue-api-gateway:8000
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_PASS=${ADMIN_PASS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - LOGGER_URL=${LOGGER_URL}
      - LOGGER_TOKEN=${LOGGER_TOKEN}

  queue-api-gateway:
    container_name: queue-api-gateway
    build:
      context: ./microservices/queue-api-gateway
      args:
        - LOGGER_URL=${LOGGER_URL:?Logger URL is required}
        - LOGGER_TOKEN=${LOGGER_TOKEN:?Logger Token is required}
    depends_on:
      - mongodb
      - rabbitmq
      - chat-agents
    ports:
      - "8000:8000"
    environment:
      - LOGGER_URL=${LOGGER_URL}
      - LOGGER_TOKEN=${LOGGER_TOKEN}
      - MONGO_HOST=mongodb://mongodb:27017/chat-agents
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672

  rabbitmq:
    container_name: chat-agents-queue
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    container_name: mongo-store
    image: mongo:bionic
    ports:
      - "27017:27017"