
const questions = [
    { question_text: "What is your full name?", category: "Personal Background" },
    { question_text: "Where are you from originally?", category: "Personal Background" },
    { question_text: "Do you have any siblings? If so, how many?", category: "Personal Background" },
    { question_text: "What's your favorite childhood memory?", category: "Personal Background" },
    { question_text: "What are your favorite hobbies or activities?", category: "Interests and Hobbies" },
    { question_text: "Do you enjoy any sports? Which ones?", category: "Interests and Hobbies" },
    { question_text: "What kind of music do you like to listen to?", category: "Interests and Hobbies" },
    { question_text: "Do you have any favorite books or authors?", category: "Interests and Hobbies" },
    { question_text: "Are you a movie or TV series fan? What's your favorite genre?", category: "Interests and Hobbies" },
    { question_text: "Do you enjoy playing video games? If yes, what are your favorite games?", category: "Interests and Hobbies" },
    { question_text: "Are you more of an early bird or a night owl?", category: "Lifestyle and Preferences" },
    { question_text: "How do you usually spend your weekends?", category: "Lifestyle and Preferences" },
    { question_text: "Do you prefer spending time indoors or outdoors?", category: "Lifestyle and Preferences" },
    { question_text: "What's your favorite way to relax after a long day?", category: "Lifestyle and Preferences" },
    { question_text: "Do you follow any particular diet or have any food preferences?", category: "Lifestyle and Preferences" },
    { question_text: "Which social media platforms do you use most frequently?", category: "Social and Cultural Interests" },
    { question_text: "Do you like attending social events, or do you prefer smaller gatherings?", category: "Social and Cultural Interests" },
    { question_text: "Are you involved in any community or volunteer activities?", category: "Social and Cultural Interests" },
    { question_text: "What's your favorite travel destination you've visited so far?", category: "Social and Cultural Interests" },
    { question_text: "If you could travel anywhere in the world, where would you go?", category: "Social and Cultural Interests" },
    { question_text: "What do you do for a living or what are you studying?", category: "Professional and Academic Background" },
    { question_text: "What subjects or fields are you passionate about?", category: "Professional and Academic Background" },
    { question_text: "Are you part of any clubs or professional organizations?", category: "Professional and Academic Background" },
    { question_text: "What are your long-term career goals?", category: "Professional and Academic Background" },
    { question_text: "Do you have any significant achievements you're proud of?", category: "Professional and Academic Background" },
    { question_text: "Are you interested in technology? If so, which areas?", category: "Technology and Gadgets" },
    { question_text: "What are your favorite apps or websites?", category: "Technology and Gadgets" },
    { question_text: "Do you prefer using a smartphone, tablet, or computer for most tasks?", category: "Technology and Gadgets" },
    { question_text: "Are you into smart home devices? If so, which ones?", category: "Technology and Gadgets" },
    { question_text: "What do you value most in life?", category: "Personal Values and Opinions" },
    { question_text: "Who is someone you admire and why?", category: "Personal Values and Opinions" },
    { question_text: "What's a cause you're passionate about?", category: "Personal Values and Opinions" },
    { question_text: "Do you have any favorite quotes or sayings?", category: "Personal Values and Opinions" },
    { question_text: "What qualities do you value most in friends and relationships?", category: "Personal Values and Opinions" },
    { question_text: "What's your idea of a perfect day?", category: "Fun and Creative Questions" },
    { question_text: "If you could have any superpower, what would it be and why?", category: "Fun and Creative Questions" },
    { question_text: "What's the most adventurous thing you've ever done?", category: "Fun and Creative Questions" },
    { question_text: "Do you have any hidden talents or skills?", category: "Fun and Creative Questions" },
    { question_text: "If you could meet any historical figure, who would it be and why?", category: "Fun and Creative Questions" },
    { question_text: "What's something on your bucket list that you haven't done yet?", category: "Fun and Creative Questions" }
  ];

export default questions;