# Add this docker file as chat-agents
version: '3'
services:
  chat-agents:
    build:
      context: .
      args:
        - LOGGER_URL=${LOGGER_URL}
        - LOGGER_TOKEN=${LOGGER_TOKEN}
        - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - LOGGER_URL=${LOGGER_URL}
      - LOGGER_TOKEN=${LOGGER_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_HOST=mongodb://mongodb:27017/chat-agents
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:bionic
    ports:
      - "27017:27017"